version: '3.8'
services:
  db:
    image: postgres
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  mongodb_container:
    image: mongo:latest
    restart: "no"
    ports:
      - 27017-27017:27017-27017
    volumes:
      - mongodb_data_container:/data/db


volumes:
  db:
    driver: local
  mongodb_data_container:

